// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protoflagtest/v1/types.proto

package protoflagtestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestEnum int32

const (
	TestEnum_TEST_ENUM_UNSPECIFIED TestEnum = 0
	TestEnum_TEST_ENUM_FIRST       TestEnum = 1
	TestEnum_TEST_ENUM_SECOND      TestEnum = 2
)

// Enum value maps for TestEnum.
var (
	TestEnum_name = map[int32]string{
		0: "TEST_ENUM_UNSPECIFIED",
		1: "TEST_ENUM_FIRST",
		2: "TEST_ENUM_SECOND",
	}
	TestEnum_value = map[string]int32{
		"TEST_ENUM_UNSPECIFIED": 0,
		"TEST_ENUM_FIRST":       1,
		"TEST_ENUM_SECOND":      2,
	}
)

func (x TestEnum) Enum() *TestEnum {
	p := new(TestEnum)
	*p = x
	return p
}

func (x TestEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_protoflagtest_v1_types_proto_enumTypes[0].Descriptor()
}

func (TestEnum) Type() protoreflect.EnumType {
	return &file_protoflagtest_v1_types_proto_enumTypes[0]
}

func (x TestEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SimpleMessage struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Foo string                 `protobuf:"bytes,1,opt,name=foo,proto3"`
	xxx_hidden_Bar string                 `protobuf:"bytes,2,opt,name=bar,proto3"`
	xxx_hidden_Baz string                 `protobuf:"bytes,3,opt,name=baz,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	mi := &file_protoflagtest_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protoflagtest_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SimpleMessage) GetFoo() string {
	if x != nil {
		return x.xxx_hidden_Foo
	}
	return ""
}

func (x *SimpleMessage) GetBar() string {
	if x != nil {
		return x.xxx_hidden_Bar
	}
	return ""
}

func (x *SimpleMessage) GetBaz() string {
	if x != nil {
		return x.xxx_hidden_Baz
	}
	return ""
}

func (x *SimpleMessage) SetFoo(v string) {
	x.xxx_hidden_Foo = v
}

func (x *SimpleMessage) SetBar(v string) {
	x.xxx_hidden_Bar = v
}

func (x *SimpleMessage) SetBaz(v string) {
	x.xxx_hidden_Baz = v
}

type SimpleMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Foo string
	Bar string
	Baz string
}

func (b0 SimpleMessage_builder) Build() *SimpleMessage {
	m0 := &SimpleMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Foo = b.Foo
	x.xxx_hidden_Bar = b.Bar
	x.xxx_hidden_Baz = b.Baz
	return m0
}

type SimpleMessageWithUsage struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Foo string                 `protobuf:"bytes,1,opt,name=foo,proto3"`
	xxx_hidden_Bar string                 `protobuf:"bytes,2,opt,name=bar,proto3"`
	xxx_hidden_Baz string                 `protobuf:"bytes,3,opt,name=baz,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimpleMessageWithUsage) Reset() {
	*x = SimpleMessageWithUsage{}
	mi := &file_protoflagtest_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMessageWithUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessageWithUsage) ProtoMessage() {}

func (x *SimpleMessageWithUsage) ProtoReflect() protoreflect.Message {
	mi := &file_protoflagtest_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SimpleMessageWithUsage) GetFoo() string {
	if x != nil {
		return x.xxx_hidden_Foo
	}
	return ""
}

func (x *SimpleMessageWithUsage) GetBar() string {
	if x != nil {
		return x.xxx_hidden_Bar
	}
	return ""
}

func (x *SimpleMessageWithUsage) GetBaz() string {
	if x != nil {
		return x.xxx_hidden_Baz
	}
	return ""
}

func (x *SimpleMessageWithUsage) SetFoo(v string) {
	x.xxx_hidden_Foo = v
}

func (x *SimpleMessageWithUsage) SetBar(v string) {
	x.xxx_hidden_Bar = v
}

func (x *SimpleMessageWithUsage) SetBaz(v string) {
	x.xxx_hidden_Baz = v
}

type SimpleMessageWithUsage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Foo string
	Bar string
	Baz string
}

func (b0 SimpleMessageWithUsage_builder) Build() *SimpleMessageWithUsage {
	m0 := &SimpleMessageWithUsage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Foo = b.Foo
	x.xxx_hidden_Bar = b.Bar
	x.xxx_hidden_Baz = b.Baz
	return m0
}

type Top struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value  string                 `protobuf:"bytes,1,opt,name=value,proto3"`
	xxx_hidden_Middle *Middle                `protobuf:"bytes,2,opt,name=middle,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Top) Reset() {
	*x = Top{}
	mi := &file_protoflagtest_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Top) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top) ProtoMessage() {}

func (x *Top) ProtoReflect() protoreflect.Message {
	mi := &file_protoflagtest_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Top) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *Top) GetMiddle() *Middle {
	if x != nil {
		return x.xxx_hidden_Middle
	}
	return nil
}

func (x *Top) SetValue(v string) {
	x.xxx_hidden_Value = v
}

func (x *Top) SetMiddle(v *Middle) {
	x.xxx_hidden_Middle = v
}

func (x *Top) HasMiddle() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Middle != nil
}

func (x *Top) ClearMiddle() {
	x.xxx_hidden_Middle = nil
}

type Top_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value  string
	Middle *Middle
}

func (b0 Top_builder) Build() *Top {
	m0 := &Top{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Middle = b.Middle
	return m0
}

type Middle struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value  string                 `protobuf:"bytes,1,opt,name=value,proto3"`
	xxx_hidden_Bottom *Bottom                `protobuf:"bytes,2,opt,name=bottom,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Middle) Reset() {
	*x = Middle{}
	mi := &file_protoflagtest_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Middle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Middle) ProtoMessage() {}

func (x *Middle) ProtoReflect() protoreflect.Message {
	mi := &file_protoflagtest_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Middle) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *Middle) GetBottom() *Bottom {
	if x != nil {
		return x.xxx_hidden_Bottom
	}
	return nil
}

func (x *Middle) SetValue(v string) {
	x.xxx_hidden_Value = v
}

func (x *Middle) SetBottom(v *Bottom) {
	x.xxx_hidden_Bottom = v
}

func (x *Middle) HasBottom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Bottom != nil
}

func (x *Middle) ClearBottom() {
	x.xxx_hidden_Bottom = nil
}

type Middle_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value  string
	Bottom *Bottom
}

func (b0 Middle_builder) Build() *Middle {
	m0 := &Middle{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Bottom = b.Bottom
	return m0
}

type Bottom struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value             string                 `protobuf:"bytes,1,opt,name=value,proto3"`
	xxx_hidden_ValueWithLongName string                 `protobuf:"bytes,2,opt,name=value_with_long_name,json=valueWithLongName,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Bottom) Reset() {
	*x = Bottom{}
	mi := &file_protoflagtest_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bottom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bottom) ProtoMessage() {}

func (x *Bottom) ProtoReflect() protoreflect.Message {
	mi := &file_protoflagtest_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Bottom) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *Bottom) GetValueWithLongName() string {
	if x != nil {
		return x.xxx_hidden_ValueWithLongName
	}
	return ""
}

func (x *Bottom) SetValue(v string) {
	x.xxx_hidden_Value = v
}

func (x *Bottom) SetValueWithLongName(v string) {
	x.xxx_hidden_ValueWithLongName = v
}

type Bottom_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value             string
	ValueWithLongName string
}

func (b0 Bottom_builder) Build() *Bottom {
	m0 := &Bottom{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_ValueWithLongName = b.ValueWithLongName
	return m0
}

type TestBase struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ValueBool        bool                   `protobuf:"varint,1,opt,name=value_bool,json=valueBool,proto3"`
	xxx_hidden_ValueInt32       int32                  `protobuf:"varint,2,opt,name=value_int32,json=valueInt32,proto3"`
	xxx_hidden_ValueSint32      int32                  `protobuf:"zigzag32,3,opt,name=value_sint32,json=valueSint32,proto3"`
	xxx_hidden_ValueSfixed32    int32                  `protobuf:"fixed32,4,opt,name=value_sfixed32,json=valueSfixed32,proto3"`
	xxx_hidden_ValueUint32      uint32                 `protobuf:"varint,5,opt,name=value_uint32,json=valueUint32,proto3"`
	xxx_hidden_ValueFixed32     uint32                 `protobuf:"fixed32,6,opt,name=value_fixed32,json=valueFixed32,proto3"`
	xxx_hidden_ValueInt64       int64                  `protobuf:"varint,7,opt,name=value_int64,json=valueInt64,proto3"`
	xxx_hidden_ValueSint64      int64                  `protobuf:"zigzag64,8,opt,name=value_sint64,json=valueSint64,proto3"`
	xxx_hidden_ValueSfixed64    int64                  `protobuf:"fixed64,9,opt,name=value_sfixed64,json=valueSfixed64,proto3"`
	xxx_hidden_ValueUint64      uint64                 `protobuf:"varint,10,opt,name=value_uint64,json=valueUint64,proto3"`
	xxx_hidden_ValueFixed64     uint64                 `protobuf:"fixed64,11,opt,name=value_fixed64,json=valueFixed64,proto3"`
	xxx_hidden_ValueFloat       float32                `protobuf:"fixed32,12,opt,name=value_float,json=valueFloat,proto3"`
	xxx_hidden_ValueDouble      float64                `protobuf:"fixed64,13,opt,name=value_double,json=valueDouble,proto3"`
	xxx_hidden_ValueString      string                 `protobuf:"bytes,14,opt,name=value_string,json=valueString,proto3"`
	xxx_hidden_ValueBytes       []byte                 `protobuf:"bytes,15,opt,name=value_bytes,json=valueBytes,proto3"`
	xxx_hidden_ValueEnum        TestEnum               `protobuf:"varint,16,opt,name=value_enum,json=valueEnum,proto3,enum=protoflagtest.v1.TestEnum"`
	xxx_hidden_ValueMessage     *TestMessage           `protobuf:"bytes,17,opt,name=value_message,json=valueMessage,proto3"`
	xxx_hidden_ValueMap         map[string]string      `protobuf:"bytes,18,rep,name=value_map,json=valueMap,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_RepeatedBool     []bool                 `protobuf:"varint,21,rep,packed,name=repeated_bool,json=repeatedBool,proto3"`
	xxx_hidden_RepeatedInt32    []int32                `protobuf:"varint,22,rep,packed,name=repeated_int32,json=repeatedInt32,proto3"`
	xxx_hidden_RepeatedSint32   []int32                `protobuf:"zigzag32,23,rep,packed,name=repeated_sint32,json=repeatedSint32,proto3"`
	xxx_hidden_RepeatedSfixed32 []int32                `protobuf:"fixed32,24,rep,packed,name=repeated_sfixed32,json=repeatedSfixed32,proto3"`
	xxx_hidden_RepeatedUint32   []uint32               `protobuf:"varint,25,rep,packed,name=repeated_uint32,json=repeatedUint32,proto3"`
	xxx_hidden_RepeatedFixed32  []uint32               `protobuf:"fixed32,26,rep,packed,name=repeated_fixed32,json=repeatedFixed32,proto3"`
	xxx_hidden_RepeatedInt64    []int64                `protobuf:"varint,27,rep,packed,name=repeated_int64,json=repeatedInt64,proto3"`
	xxx_hidden_RepeatedSint64   []int64                `protobuf:"zigzag64,28,rep,packed,name=repeated_sint64,json=repeatedSint64,proto3"`
	xxx_hidden_RepeatedSfixed64 []int64                `protobuf:"fixed64,29,rep,packed,name=repeated_sfixed64,json=repeatedSfixed64,proto3"`
	xxx_hidden_RepeatedUint64   []uint64               `protobuf:"varint,30,rep,packed,name=repeated_uint64,json=repeatedUint64,proto3"`
	xxx_hidden_RepeatedFixed64  []uint64               `protobuf:"fixed64,31,rep,packed,name=repeated_fixed64,json=repeatedFixed64,proto3"`
	xxx_hidden_RepeatedFloat    []float32              `protobuf:"fixed32,32,rep,packed,name=repeated_float,json=repeatedFloat,proto3"`
	xxx_hidden_RepeatedDouble   []float64              `protobuf:"fixed64,33,rep,packed,name=repeated_double,json=repeatedDouble,proto3"`
	xxx_hidden_RepeatedString   []string               `protobuf:"bytes,34,rep,name=repeated_string,json=repeatedString,proto3"`
	xxx_hidden_RepeatedBytes    [][]byte               `protobuf:"bytes,35,rep,name=repeated_bytes,json=repeatedBytes,proto3"`
	xxx_hidden_RepeatedEnum     []TestEnum             `protobuf:"varint,36,rep,packed,name=repeated_enum,json=repeatedEnum,proto3,enum=protoflagtest.v1.TestEnum"`
	xxx_hidden_RepeatedMessage  *[]*TestMessage        `protobuf:"bytes,37,rep,name=repeated_message,json=repeatedMessage,proto3"`
	xxx_hidden_ValueSkip        int32                  `protobuf:"varint,40,opt,name=value_skip,json=valueSkip,proto3"`
	xxx_hidden_RepeatedSkip     []int32                `protobuf:"varint,41,rep,packed,name=repeated_skip,json=repeatedSkip,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *TestBase) Reset() {
	*x = TestBase{}
	mi := &file_protoflagtest_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestBase) ProtoMessage() {}

func (x *TestBase) ProtoReflect() protoreflect.Message {
	mi := &file_protoflagtest_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TestBase) GetValueBool() bool {
	if x != nil {
		return x.xxx_hidden_ValueBool
	}
	return false
}

func (x *TestBase) GetValueInt32() int32 {
	if x != nil {
		return x.xxx_hidden_ValueInt32
	}
	return 0
}

func (x *TestBase) GetValueSint32() int32 {
	if x != nil {
		return x.xxx_hidden_ValueSint32
	}
	return 0
}

func (x *TestBase) GetValueSfixed32() int32 {
	if x != nil {
		return x.xxx_hidden_ValueSfixed32
	}
	return 0
}

func (x *TestBase) GetValueUint32() uint32 {
	if x != nil {
		return x.xxx_hidden_ValueUint32
	}
	return 0
}

func (x *TestBase) GetValueFixed32() uint32 {
	if x != nil {
		return x.xxx_hidden_ValueFixed32
	}
	return 0
}

func (x *TestBase) GetValueInt64() int64 {
	if x != nil {
		return x.xxx_hidden_ValueInt64
	}
	return 0
}

func (x *TestBase) GetValueSint64() int64 {
	if x != nil {
		return x.xxx_hidden_ValueSint64
	}
	return 0
}

func (x *TestBase) GetValueSfixed64() int64 {
	if x != nil {
		return x.xxx_hidden_ValueSfixed64
	}
	return 0
}

func (x *TestBase) GetValueUint64() uint64 {
	if x != nil {
		return x.xxx_hidden_ValueUint64
	}
	return 0
}

func (x *TestBase) GetValueFixed64() uint64 {
	if x != nil {
		return x.xxx_hidden_ValueFixed64
	}
	return 0
}

func (x *TestBase) GetValueFloat() float32 {
	if x != nil {
		return x.xxx_hidden_ValueFloat
	}
	return 0
}

func (x *TestBase) GetValueDouble() float64 {
	if x != nil {
		return x.xxx_hidden_ValueDouble
	}
	return 0
}

func (x *TestBase) GetValueString() string {
	if x != nil {
		return x.xxx_hidden_ValueString
	}
	return ""
}

func (x *TestBase) GetValueBytes() []byte {
	if x != nil {
		return x.xxx_hidden_ValueBytes
	}
	return nil
}

func (x *TestBase) GetValueEnum() TestEnum {
	if x != nil {
		return x.xxx_hidden_ValueEnum
	}
	return TestEnum_TEST_ENUM_UNSPECIFIED
}

func (x *TestBase) GetValueMessage() *TestMessage {
	if x != nil {
		return x.xxx_hidden_ValueMessage
	}
	return nil
}

func (x *TestBase) GetValueMap() map[string]string {
	if x != nil {
		return x.xxx_hidden_ValueMap
	}
	return nil
}

func (x *TestBase) GetRepeatedBool() []bool {
	if x != nil {
		return x.xxx_hidden_RepeatedBool
	}
	return nil
}

func (x *TestBase) GetRepeatedInt32() []int32 {
	if x != nil {
		return x.xxx_hidden_RepeatedInt32
	}
	return nil
}

func (x *TestBase) GetRepeatedSint32() []int32 {
	if x != nil {
		return x.xxx_hidden_RepeatedSint32
	}
	return nil
}

func (x *TestBase) GetRepeatedSfixed32() []int32 {
	if x != nil {
		return x.xxx_hidden_RepeatedSfixed32
	}
	return nil
}

func (x *TestBase) GetRepeatedUint32() []uint32 {
	if x != nil {
		return x.xxx_hidden_RepeatedUint32
	}
	return nil
}

func (x *TestBase) GetRepeatedFixed32() []uint32 {
	if x != nil {
		return x.xxx_hidden_RepeatedFixed32
	}
	return nil
}

func (x *TestBase) GetRepeatedInt64() []int64 {
	if x != nil {
		return x.xxx_hidden_RepeatedInt64
	}
	return nil
}

func (x *TestBase) GetRepeatedSint64() []int64 {
	if x != nil {
		return x.xxx_hidden_RepeatedSint64
	}
	return nil
}

func (x *TestBase) GetRepeatedSfixed64() []int64 {
	if x != nil {
		return x.xxx_hidden_RepeatedSfixed64
	}
	return nil
}

func (x *TestBase) GetRepeatedUint64() []uint64 {
	if x != nil {
		return x.xxx_hidden_RepeatedUint64
	}
	return nil
}

func (x *TestBase) GetRepeatedFixed64() []uint64 {
	if x != nil {
		return x.xxx_hidden_RepeatedFixed64
	}
	return nil
}

func (x *TestBase) GetRepeatedFloat() []float32 {
	if x != nil {
		return x.xxx_hidden_RepeatedFloat
	}
	return nil
}

func (x *TestBase) GetRepeatedDouble() []float64 {
	if x != nil {
		return x.xxx_hidden_RepeatedDouble
	}
	return nil
}

func (x *TestBase) GetRepeatedString() []string {
	if x != nil {
		return x.xxx_hidden_RepeatedString
	}
	return nil
}

func (x *TestBase) GetRepeatedBytes() [][]byte {
	if x != nil {
		return x.xxx_hidden_RepeatedBytes
	}
	return nil
}

func (x *TestBase) GetRepeatedEnum() []TestEnum {
	if x != nil {
		return x.xxx_hidden_RepeatedEnum
	}
	return nil
}

func (x *TestBase) GetRepeatedMessage() []*TestMessage {
	if x != nil {
		if x.xxx_hidden_RepeatedMessage != nil {
			return *x.xxx_hidden_RepeatedMessage
		}
	}
	return nil
}

func (x *TestBase) GetValueSkip() int32 {
	if x != nil {
		return x.xxx_hidden_ValueSkip
	}
	return 0
}

func (x *TestBase) GetRepeatedSkip() []int32 {
	if x != nil {
		return x.xxx_hidden_RepeatedSkip
	}
	return nil
}

func (x *TestBase) SetValueBool(v bool) {
	x.xxx_hidden_ValueBool = v
}

func (x *TestBase) SetValueInt32(v int32) {
	x.xxx_hidden_ValueInt32 = v
}

func (x *TestBase) SetValueSint32(v int32) {
	x.xxx_hidden_ValueSint32 = v
}

func (x *TestBase) SetValueSfixed32(v int32) {
	x.xxx_hidden_ValueSfixed32 = v
}

func (x *TestBase) SetValueUint32(v uint32) {
	x.xxx_hidden_ValueUint32 = v
}

func (x *TestBase) SetValueFixed32(v uint32) {
	x.xxx_hidden_ValueFixed32 = v
}

func (x *TestBase) SetValueInt64(v int64) {
	x.xxx_hidden_ValueInt64 = v
}

func (x *TestBase) SetValueSint64(v int64) {
	x.xxx_hidden_ValueSint64 = v
}

func (x *TestBase) SetValueSfixed64(v int64) {
	x.xxx_hidden_ValueSfixed64 = v
}

func (x *TestBase) SetValueUint64(v uint64) {
	x.xxx_hidden_ValueUint64 = v
}

func (x *TestBase) SetValueFixed64(v uint64) {
	x.xxx_hidden_ValueFixed64 = v
}

func (x *TestBase) SetValueFloat(v float32) {
	x.xxx_hidden_ValueFloat = v
}

func (x *TestBase) SetValueDouble(v float64) {
	x.xxx_hidden_ValueDouble = v
}

func (x *TestBase) SetValueString(v string) {
	x.xxx_hidden_ValueString = v
}

func (x *TestBase) SetValueBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ValueBytes = v
}

func (x *TestBase) SetValueEnum(v TestEnum) {
	x.xxx_hidden_ValueEnum = v
}

func (x *TestBase) SetValueMessage(v *TestMessage) {
	x.xxx_hidden_ValueMessage = v
}

func (x *TestBase) SetValueMap(v map[string]string) {
	x.xxx_hidden_ValueMap = v
}

func (x *TestBase) SetRepeatedBool(v []bool) {
	x.xxx_hidden_RepeatedBool = v
}

func (x *TestBase) SetRepeatedInt32(v []int32) {
	x.xxx_hidden_RepeatedInt32 = v
}

func (x *TestBase) SetRepeatedSint32(v []int32) {
	x.xxx_hidden_RepeatedSint32 = v
}

func (x *TestBase) SetRepeatedSfixed32(v []int32) {
	x.xxx_hidden_RepeatedSfixed32 = v
}

func (x *TestBase) SetRepeatedUint32(v []uint32) {
	x.xxx_hidden_RepeatedUint32 = v
}

func (x *TestBase) SetRepeatedFixed32(v []uint32) {
	x.xxx_hidden_RepeatedFixed32 = v
}

func (x *TestBase) SetRepeatedInt64(v []int64) {
	x.xxx_hidden_RepeatedInt64 = v
}

func (x *TestBase) SetRepeatedSint64(v []int64) {
	x.xxx_hidden_RepeatedSint64 = v
}

func (x *TestBase) SetRepeatedSfixed64(v []int64) {
	x.xxx_hidden_RepeatedSfixed64 = v
}

func (x *TestBase) SetRepeatedUint64(v []uint64) {
	x.xxx_hidden_RepeatedUint64 = v
}

func (x *TestBase) SetRepeatedFixed64(v []uint64) {
	x.xxx_hidden_RepeatedFixed64 = v
}

func (x *TestBase) SetRepeatedFloat(v []float32) {
	x.xxx_hidden_RepeatedFloat = v
}

func (x *TestBase) SetRepeatedDouble(v []float64) {
	x.xxx_hidden_RepeatedDouble = v
}

func (x *TestBase) SetRepeatedString(v []string) {
	x.xxx_hidden_RepeatedString = v
}

func (x *TestBase) SetRepeatedBytes(v [][]byte) {
	x.xxx_hidden_RepeatedBytes = v
}

func (x *TestBase) SetRepeatedEnum(v []TestEnum) {
	x.xxx_hidden_RepeatedEnum = v
}

func (x *TestBase) SetRepeatedMessage(v []*TestMessage) {
	x.xxx_hidden_RepeatedMessage = &v
}

func (x *TestBase) SetValueSkip(v int32) {
	x.xxx_hidden_ValueSkip = v
}

func (x *TestBase) SetRepeatedSkip(v []int32) {
	x.xxx_hidden_RepeatedSkip = v
}

func (x *TestBase) HasValueMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ValueMessage != nil
}

func (x *TestBase) ClearValueMessage() {
	x.xxx_hidden_ValueMessage = nil
}

type TestBase_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ValueBool        bool
	ValueInt32       int32
	ValueSint32      int32
	ValueSfixed32    int32
	ValueUint32      uint32
	ValueFixed32     uint32
	ValueInt64       int64
	ValueSint64      int64
	ValueSfixed64    int64
	ValueUint64      uint64
	ValueFixed64     uint64
	ValueFloat       float32
	ValueDouble      float64
	ValueString      string
	ValueBytes       []byte
	ValueEnum        TestEnum
	ValueMessage     *TestMessage
	ValueMap         map[string]string
	RepeatedBool     []bool
	RepeatedInt32    []int32
	RepeatedSint32   []int32
	RepeatedSfixed32 []int32
	RepeatedUint32   []uint32
	RepeatedFixed32  []uint32
	RepeatedInt64    []int64
	RepeatedSint64   []int64
	RepeatedSfixed64 []int64
	RepeatedUint64   []uint64
	RepeatedFixed64  []uint64
	RepeatedFloat    []float32
	RepeatedDouble   []float64
	RepeatedString   []string
	RepeatedBytes    [][]byte
	RepeatedEnum     []TestEnum
	RepeatedMessage  []*TestMessage
	ValueSkip        int32
	RepeatedSkip     []int32
}

func (b0 TestBase_builder) Build() *TestBase {
	m0 := &TestBase{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ValueBool = b.ValueBool
	x.xxx_hidden_ValueInt32 = b.ValueInt32
	x.xxx_hidden_ValueSint32 = b.ValueSint32
	x.xxx_hidden_ValueSfixed32 = b.ValueSfixed32
	x.xxx_hidden_ValueUint32 = b.ValueUint32
	x.xxx_hidden_ValueFixed32 = b.ValueFixed32
	x.xxx_hidden_ValueInt64 = b.ValueInt64
	x.xxx_hidden_ValueSint64 = b.ValueSint64
	x.xxx_hidden_ValueSfixed64 = b.ValueSfixed64
	x.xxx_hidden_ValueUint64 = b.ValueUint64
	x.xxx_hidden_ValueFixed64 = b.ValueFixed64
	x.xxx_hidden_ValueFloat = b.ValueFloat
	x.xxx_hidden_ValueDouble = b.ValueDouble
	x.xxx_hidden_ValueString = b.ValueString
	x.xxx_hidden_ValueBytes = b.ValueBytes
	x.xxx_hidden_ValueEnum = b.ValueEnum
	x.xxx_hidden_ValueMessage = b.ValueMessage
	x.xxx_hidden_ValueMap = b.ValueMap
	x.xxx_hidden_RepeatedBool = b.RepeatedBool
	x.xxx_hidden_RepeatedInt32 = b.RepeatedInt32
	x.xxx_hidden_RepeatedSint32 = b.RepeatedSint32
	x.xxx_hidden_RepeatedSfixed32 = b.RepeatedSfixed32
	x.xxx_hidden_RepeatedUint32 = b.RepeatedUint32
	x.xxx_hidden_RepeatedFixed32 = b.RepeatedFixed32
	x.xxx_hidden_RepeatedInt64 = b.RepeatedInt64
	x.xxx_hidden_RepeatedSint64 = b.RepeatedSint64
	x.xxx_hidden_RepeatedSfixed64 = b.RepeatedSfixed64
	x.xxx_hidden_RepeatedUint64 = b.RepeatedUint64
	x.xxx_hidden_RepeatedFixed64 = b.RepeatedFixed64
	x.xxx_hidden_RepeatedFloat = b.RepeatedFloat
	x.xxx_hidden_RepeatedDouble = b.RepeatedDouble
	x.xxx_hidden_RepeatedString = b.RepeatedString
	x.xxx_hidden_RepeatedBytes = b.RepeatedBytes
	x.xxx_hidden_RepeatedEnum = b.RepeatedEnum
	x.xxx_hidden_RepeatedMessage = &b.RepeatedMessage
	x.xxx_hidden_ValueSkip = b.ValueSkip
	x.xxx_hidden_RepeatedSkip = b.RepeatedSkip
	return m0
}

type TestMessage struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value string                 `protobuf:"bytes,1,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_protoflagtest_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protoflagtest_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TestMessage) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *TestMessage) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type TestMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value string
}

func (b0 TestMessage_builder) Build() *TestMessage {
	m0 := &TestMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

var file_protoflagtest_v1_types_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         7366260,
		Name:          "protoflagtest.v1.usage",
		Tag:           "bytes,7366260,opt,name=usage",
		Filename:      "protoflagtest/v1/types.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string usage = 7366260;
	E_Usage = &file_protoflagtest_v1_types_proto_extTypes[0] // 0x706674 - pft - proto flag test
)

var File_protoflagtest_v1_types_proto protoreflect.FileDescriptor

const file_protoflagtest_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1cprotoflagtest/v1/types.proto\x12\x10protoflagtest.v1\x1a google/protobuf/descriptor.proto\"E\n" +
	"\rSimpleMessage\x12\x10\n" +
	"\x03foo\x18\x01 \x01(\tR\x03foo\x12\x10\n" +
	"\x03bar\x18\x02 \x01(\tR\x03bar\x12\x10\n" +
	"\x03baz\x18\x03 \x01(\tR\x03baz\"\xd8\x01\n" +
	"\x16SimpleMessageWithUsage\x12>\n" +
	"\x03foo\x18\x01 \x01(\tB,\xa2\xe7\x8c\x1c'Usage of flag associated with foo fieldR\x03foo\x12>\n" +
	"\x03bar\x18\x02 \x01(\tB,\xa2\xe7\x8c\x1c'Usage of flag associated with bar fieldR\x03bar\x12>\n" +
	"\x03baz\x18\x03 \x01(\tB,\xa2\xe7\x8c\x1c'Usage of flag associated with baz fieldR\x03baz\"M\n" +
	"\x03Top\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x120\n" +
	"\x06middle\x18\x02 \x01(\v2\x18.protoflagtest.v1.MiddleR\x06middle\"P\n" +
	"\x06Middle\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x120\n" +
	"\x06bottom\x18\x02 \x01(\v2\x18.protoflagtest.v1.BottomR\x06bottom\"O\n" +
	"\x06Bottom\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12/\n" +
	"\x14value_with_long_name\x18\x02 \x01(\tR\x11valueWithLongName\"\xd0\f\n" +
	"\bTestBase\x12\x1d\n" +
	"\n" +
	"value_bool\x18\x01 \x01(\bR\tvalueBool\x12\x1f\n" +
	"\vvalue_int32\x18\x02 \x01(\x05R\n" +
	"valueInt32\x12!\n" +
	"\fvalue_sint32\x18\x03 \x01(\x11R\vvalueSint32\x12%\n" +
	"\x0evalue_sfixed32\x18\x04 \x01(\x0fR\rvalueSfixed32\x12!\n" +
	"\fvalue_uint32\x18\x05 \x01(\rR\vvalueUint32\x12#\n" +
	"\rvalue_fixed32\x18\x06 \x01(\aR\fvalueFixed32\x12\x1f\n" +
	"\vvalue_int64\x18\a \x01(\x03R\n" +
	"valueInt64\x12!\n" +
	"\fvalue_sint64\x18\b \x01(\x12R\vvalueSint64\x12%\n" +
	"\x0evalue_sfixed64\x18\t \x01(\x10R\rvalueSfixed64\x12!\n" +
	"\fvalue_uint64\x18\n" +
	" \x01(\x04R\vvalueUint64\x12#\n" +
	"\rvalue_fixed64\x18\v \x01(\x06R\fvalueFixed64\x12\x1f\n" +
	"\vvalue_float\x18\f \x01(\x02R\n" +
	"valueFloat\x12!\n" +
	"\fvalue_double\x18\r \x01(\x01R\vvalueDouble\x12!\n" +
	"\fvalue_string\x18\x0e \x01(\tR\vvalueString\x12\x1f\n" +
	"\vvalue_bytes\x18\x0f \x01(\fR\n" +
	"valueBytes\x129\n" +
	"\n" +
	"value_enum\x18\x10 \x01(\x0e2\x1a.protoflagtest.v1.TestEnumR\tvalueEnum\x12B\n" +
	"\rvalue_message\x18\x11 \x01(\v2\x1d.protoflagtest.v1.TestMessageR\fvalueMessage\x12E\n" +
	"\tvalue_map\x18\x12 \x03(\v2(.protoflagtest.v1.TestBase.ValueMapEntryR\bvalueMap\x12#\n" +
	"\rrepeated_bool\x18\x15 \x03(\bR\frepeatedBool\x12%\n" +
	"\x0erepeated_int32\x18\x16 \x03(\x05R\rrepeatedInt32\x12'\n" +
	"\x0frepeated_sint32\x18\x17 \x03(\x11R\x0erepeatedSint32\x12+\n" +
	"\x11repeated_sfixed32\x18\x18 \x03(\x0fR\x10repeatedSfixed32\x12'\n" +
	"\x0frepeated_uint32\x18\x19 \x03(\rR\x0erepeatedUint32\x12)\n" +
	"\x10repeated_fixed32\x18\x1a \x03(\aR\x0frepeatedFixed32\x12%\n" +
	"\x0erepeated_int64\x18\x1b \x03(\x03R\rrepeatedInt64\x12'\n" +
	"\x0frepeated_sint64\x18\x1c \x03(\x12R\x0erepeatedSint64\x12+\n" +
	"\x11repeated_sfixed64\x18\x1d \x03(\x10R\x10repeatedSfixed64\x12'\n" +
	"\x0frepeated_uint64\x18\x1e \x03(\x04R\x0erepeatedUint64\x12)\n" +
	"\x10repeated_fixed64\x18\x1f \x03(\x06R\x0frepeatedFixed64\x12%\n" +
	"\x0erepeated_float\x18  \x03(\x02R\rrepeatedFloat\x12'\n" +
	"\x0frepeated_double\x18! \x03(\x01R\x0erepeatedDouble\x12'\n" +
	"\x0frepeated_string\x18\" \x03(\tR\x0erepeatedString\x12%\n" +
	"\x0erepeated_bytes\x18# \x03(\fR\rrepeatedBytes\x12?\n" +
	"\rrepeated_enum\x18$ \x03(\x0e2\x1a.protoflagtest.v1.TestEnumR\frepeatedEnum\x12H\n" +
	"\x10repeated_message\x18% \x03(\v2\x1d.protoflagtest.v1.TestMessageR\x0frepeatedMessage\x12\x1d\n" +
	"\n" +
	"value_skip\x18( \x01(\x05R\tvalueSkip\x12#\n" +
	"\rrepeated_skip\x18) \x03(\x05R\frepeatedSkip\x1a;\n" +
	"\rValueMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\vTestMessage\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value*P\n" +
	"\bTestEnum\x12\x19\n" +
	"\x15TEST_ENUM_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTEST_ENUM_FIRST\x10\x01\x12\x14\n" +
	"\x10TEST_ENUM_SECOND\x10\x02:6\n" +
	"\x05usage\x12\x1d.google.protobuf.FieldOptions\x18\xf4\xcc\xc1\x03 \x01(\tR\x05usageB\xca\x01\n" +
	"\x14com.protoflagtest.v1B\n" +
	"TypesProtoP\x01ZEgithub.com/daishe/protoflag/internal/protoflagtest/v1;protoflagtestv1\xa2\x02\x03PXX\xaa\x02\x10Protoflagtest.V1\xca\x02\x10Protoflagtest\\V1\xe2\x02\x1cProtoflagtest\\V1\\GPBMetadata\xea\x02\x11Protoflagtest::V1b\x06proto3"

var file_protoflagtest_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protoflagtest_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protoflagtest_v1_types_proto_goTypes = []any{
	(TestEnum)(0),                     // 0: protoflagtest.v1.TestEnum
	(*SimpleMessage)(nil),             // 1: protoflagtest.v1.SimpleMessage
	(*SimpleMessageWithUsage)(nil),    // 2: protoflagtest.v1.SimpleMessageWithUsage
	(*Top)(nil),                       // 3: protoflagtest.v1.Top
	(*Middle)(nil),                    // 4: protoflagtest.v1.Middle
	(*Bottom)(nil),                    // 5: protoflagtest.v1.Bottom
	(*TestBase)(nil),                  // 6: protoflagtest.v1.TestBase
	(*TestMessage)(nil),               // 7: protoflagtest.v1.TestMessage
	nil,                               // 8: protoflagtest.v1.TestBase.ValueMapEntry
	(*descriptorpb.FieldOptions)(nil), // 9: google.protobuf.FieldOptions
}
var file_protoflagtest_v1_types_proto_depIdxs = []int32{
	4, // 0: protoflagtest.v1.Top.middle:type_name -> protoflagtest.v1.Middle
	5, // 1: protoflagtest.v1.Middle.bottom:type_name -> protoflagtest.v1.Bottom
	0, // 2: protoflagtest.v1.TestBase.value_enum:type_name -> protoflagtest.v1.TestEnum
	7, // 3: protoflagtest.v1.TestBase.value_message:type_name -> protoflagtest.v1.TestMessage
	8, // 4: protoflagtest.v1.TestBase.value_map:type_name -> protoflagtest.v1.TestBase.ValueMapEntry
	0, // 5: protoflagtest.v1.TestBase.repeated_enum:type_name -> protoflagtest.v1.TestEnum
	7, // 6: protoflagtest.v1.TestBase.repeated_message:type_name -> protoflagtest.v1.TestMessage
	9, // 7: protoflagtest.v1.usage:extendee -> google.protobuf.FieldOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	7, // [7:8] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protoflagtest_v1_types_proto_init() }
func file_protoflagtest_v1_types_proto_init() {
	if File_protoflagtest_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoflagtest_v1_types_proto_rawDesc), len(file_protoflagtest_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_protoflagtest_v1_types_proto_goTypes,
		DependencyIndexes: file_protoflagtest_v1_types_proto_depIdxs,
		EnumInfos:         file_protoflagtest_v1_types_proto_enumTypes,
		MessageInfos:      file_protoflagtest_v1_types_proto_msgTypes,
		ExtensionInfos:    file_protoflagtest_v1_types_proto_extTypes,
	}.Build()
	File_protoflagtest_v1_types_proto = out.File
	file_protoflagtest_v1_types_proto_goTypes = nil
	file_protoflagtest_v1_types_proto_depIdxs = nil
}
