// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: simplecurl/types/v1/types.proto

package typesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Url     *Url                   `protobuf:"bytes,1,opt,name=url,proto3"`
	xxx_hidden_Verbose bool                   `protobuf:"varint,2,opt,name=verbose,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_simplecurl_types_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_simplecurl_types_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Config) GetUrl() *Url {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return nil
}

func (x *Config) GetVerbose() bool {
	if x != nil {
		return x.xxx_hidden_Verbose
	}
	return false
}

func (x *Config) SetUrl(v *Url) {
	x.xxx_hidden_Url = v
}

func (x *Config) SetVerbose(v bool) {
	x.xxx_hidden_Verbose = v
}

func (x *Config) HasUrl() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Url != nil
}

func (x *Config) ClearUrl() {
	x.xxx_hidden_Url = nil
}

type Config_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Url     *Url
	Verbose bool
}

func (b0 Config_builder) Build() *Config {
	m0 := &Config{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_Verbose = b.Verbose
	return m0
}

type Url struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Scheme string                 `protobuf:"bytes,1,opt,name=scheme,proto3"`
	xxx_hidden_Host   string                 `protobuf:"bytes,2,opt,name=host,proto3"`
	xxx_hidden_Port   int32                  `protobuf:"varint,3,opt,name=port,proto3"`
	xxx_hidden_Path   string                 `protobuf:"bytes,4,opt,name=path,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Url) Reset() {
	*x = Url{}
	mi := &file_simplecurl_types_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_simplecurl_types_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Url) GetScheme() string {
	if x != nil {
		return x.xxx_hidden_Scheme
	}
	return ""
}

func (x *Url) GetHost() string {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return ""
}

func (x *Url) GetPort() int32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *Url) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *Url) SetScheme(v string) {
	x.xxx_hidden_Scheme = v
}

func (x *Url) SetHost(v string) {
	x.xxx_hidden_Host = v
}

func (x *Url) SetPort(v int32) {
	x.xxx_hidden_Port = v
}

func (x *Url) SetPath(v string) {
	x.xxx_hidden_Path = v
}

type Url_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Scheme string
	Host   string
	Port   int32
	Path   string
}

func (b0 Url_builder) Build() *Url {
	m0 := &Url{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Scheme = b.Scheme
	x.xxx_hidden_Host = b.Host
	x.xxx_hidden_Port = b.Port
	x.xxx_hidden_Path = b.Path
	return m0
}

var file_simplecurl_types_v1_types_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         7562100,
		Name:          "simplecurl.types.v1.usage",
		Tag:           "bytes,7562100,opt,name=usage",
		Filename:      "simplecurl/types/v1/types.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string usage = 7562100;
	E_Usage = &file_simplecurl_types_v1_types_proto_extTypes[0] // 0x736374 - sct - simple curl types
)

var File_simplecurl_types_v1_types_proto protoreflect.FileDescriptor

const file_simplecurl_types_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1fsimplecurl/types/v1/types.proto\x12\x13simplecurl.types.v1\x1a google/protobuf/descriptor.proto\"\xb7\x01\n" +
	"\x06Config\x12E\n" +
	"\x03url\x18\x01 \x01(\v2\x18.simplecurl.types.v1.UrlB\x19\xa2\xb7\xec\x1c\x14URL of to connect toR\x03url\x12f\n" +
	"\averbose\x18\x02 \x01(\bBL\xa2\xb7\xec\x1cGControls if the data returned by the server should be printed to stdoutR\averbose\"\xf0\x01\n" +
	"\x03Url\x12;\n" +
	"\x06scheme\x18\x01 \x01(\tB#\xa2\xb7\xec\x1c\x1escheme (ex. 'http' or 'https')R\x06scheme\x12\x1d\n" +
	"\x04host\x18\x02 \x01(\tB\t\xa2\xb7\xec\x1c\x04hostR\x04host\x12[\n" +
	"\x04port\x18\x03 \x01(\x05BG\xa2\xb7\xec\x1cBoptional port (when not specified port is derived from the scheme)R\x04port\x120\n" +
	"\x04path\x18\x04 \x01(\tB\x1c\xa2\xb7\xec\x1c\x17requested resource pathR\x04path:6\n" +
	"\x05usage\x12\x1d.google.protobuf.FieldOptions\x18\xf4\xc6\xcd\x03 \x01(\tR\x05usageB\xd5\x01\n" +
	"\x17com.simplecurl.types.v1B\n" +
	"TypesProtoP\x01Z@github.com/daishe/protoflag/examples/simplecurl/types/v1;typesv1\xa2\x02\x03STX\xaa\x02\x13Simplecurl.Types.V1\xca\x02\x13Simplecurl\\Types\\V1\xe2\x02\x1fSimplecurl\\Types\\V1\\GPBMetadata\xea\x02\x15Simplecurl::Types::V1b\x06proto3"

var file_simplecurl_types_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_simplecurl_types_v1_types_proto_goTypes = []any{
	(*Config)(nil),                    // 0: simplecurl.types.v1.Config
	(*Url)(nil),                       // 1: simplecurl.types.v1.Url
	(*descriptorpb.FieldOptions)(nil), // 2: google.protobuf.FieldOptions
}
var file_simplecurl_types_v1_types_proto_depIdxs = []int32{
	1, // 0: simplecurl.types.v1.Config.url:type_name -> simplecurl.types.v1.Url
	2, // 1: simplecurl.types.v1.usage:extendee -> google.protobuf.FieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_simplecurl_types_v1_types_proto_init() }
func file_simplecurl_types_v1_types_proto_init() {
	if File_simplecurl_types_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simplecurl_types_v1_types_proto_rawDesc), len(file_simplecurl_types_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_simplecurl_types_v1_types_proto_goTypes,
		DependencyIndexes: file_simplecurl_types_v1_types_proto_depIdxs,
		MessageInfos:      file_simplecurl_types_v1_types_proto_msgTypes,
		ExtensionInfos:    file_simplecurl_types_v1_types_proto_extTypes,
	}.Build()
	File_simplecurl_types_v1_types_proto = out.File
	file_simplecurl_types_v1_types_proto_goTypes = nil
	file_simplecurl_types_v1_types_proto_depIdxs = nil
}
